#MODEL:
num_classes: 2
ignore_value: 255
dino_version: 2
dinov2_size: base

#OPTIM:
epochs: 200
lr: 0.00001
momentum: 0.9
weight_decay: 0.0001
bn_weight_decay: False
bn_precise_stats: False
bn_precise_num_samples: 600
lr_scheduler: poly
poly_power: 0.9
warmup_iters: 10
warmup_factor: 0.1

#TRAIN:
mixed_precision: False
run: 1
RNG_seed: 0
loss_type: cross_entropy
exclude_classes: []

#dataset
dataset_name: disaster
split_file: datasets/disaster_10shot_splits.json
batch_size: 1 # For few-shot, batch size is often 1
train_min_size: 512
train_max_size: 512
train_crop_size: [512,512]
val_input_size: [512,512]
val_label_size: [512, 512]
aug_mode: None # Bypassing PIL-based augmentations
num_workers: 8
class_uniform_pct: 0.0
train_split: 'support' # Use the support set for training/fine-tuning
val_split: 'query'   # Use the query set for validation
max_eval: 40 # Corresponds to the query set size
eval_print_every: 10
train_print_every: 10

#checkpoint
eval_every_k_epochs: 10
eval_last_k_epochs: 5
dataset_dir : ../_datasets/Exp_Disaster_Few-Shot # Relative path to dataset
save_dir: ./exp/models_disaster/
model_path : ./pretrain
model_repo_path : ./exp/
